// Package internal provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package internal

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// NewSubdomainResponse New Subdomain Response.
type NewSubdomainResponse struct {
	// Id Subdomain ID.
	Id openapi_types.UUID `json:"id"`

	// Token Control Token.
	Token string `json:"token"`
}

// OverviewResponse defines model for OverviewResponse.
type OverviewResponse struct {
	// ClientIp The clients IP address.
	ClientIp string `json:"client_ip"`

	// Version Server Version.
	Version string `json:"version"`
}

// SubdomainAcmeChallengeRequest Subdomain ACME Challenge Request.
type SubdomainAcmeChallengeRequest struct {
	// Token Control Token.
	Token string `json:"token"`

	// Values ACME Tokens.
	Values []string `json:"values"`
}

// SubdomainAcmeChallengeJSONRequestBody defines body for SubdomainAcmeChallenge for application/json ContentType.
type SubdomainAcmeChallengeJSONRequestBody = SubdomainAcmeChallengeRequest

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetOverview request
	GetOverview(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GenerateSubdomain request
	GenerateSubdomain(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// SubdomainAcmeChallenge request with any body
	SubdomainAcmeChallengeWithBody(ctx context.Context, subdomainId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	SubdomainAcmeChallenge(ctx context.Context, subdomainId openapi_types.UUID, body SubdomainAcmeChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetOverview(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetOverviewRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GenerateSubdomain(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGenerateSubdomainRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubdomainAcmeChallengeWithBody(ctx context.Context, subdomainId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubdomainAcmeChallengeRequestWithBody(c.Server, subdomainId, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) SubdomainAcmeChallenge(ctx context.Context, subdomainId openapi_types.UUID, body SubdomainAcmeChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewSubdomainAcmeChallengeRequest(c.Server, subdomainId, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetOverviewRequest generates requests for GetOverview
func NewGetOverviewRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGenerateSubdomainRequest generates requests for GenerateSubdomain
func NewGenerateSubdomainRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/subdomain")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewSubdomainAcmeChallengeRequest calls the generic SubdomainAcmeChallenge builder with application/json body
func NewSubdomainAcmeChallengeRequest(server string, subdomainId openapi_types.UUID, body SubdomainAcmeChallengeJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewSubdomainAcmeChallengeRequestWithBody(server, subdomainId, "application/json", bodyReader)
}

// NewSubdomainAcmeChallengeRequestWithBody generates requests for SubdomainAcmeChallenge with any type of body
func NewSubdomainAcmeChallengeRequestWithBody(server string, subdomainId openapi_types.UUID, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "subdomainId", runtime.ParamLocationPath, subdomainId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/subdomain/%s/acme-challenge", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetOverview request
	GetOverviewWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOverviewResponse, error)

	// GenerateSubdomain request
	GenerateSubdomainWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GenerateSubdomainResponse, error)

	// SubdomainAcmeChallenge request with any body
	SubdomainAcmeChallengeWithBodyWithResponse(ctx context.Context, subdomainId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubdomainAcmeChallengeResponse, error)

	SubdomainAcmeChallengeWithResponse(ctx context.Context, subdomainId openapi_types.UUID, body SubdomainAcmeChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*SubdomainAcmeChallengeResponse, error)
}

type GetOverviewResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *OverviewResponse
}

// Status returns HTTPResponse.Status
func (r GetOverviewResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetOverviewResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GenerateSubdomainResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *NewSubdomainResponse
	JSON429      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r GenerateSubdomainResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GenerateSubdomainResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type SubdomainAcmeChallengeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON403      *ErrorResponse
	JSON429      *ErrorResponse
}

// Status returns HTTPResponse.Status
func (r SubdomainAcmeChallengeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r SubdomainAcmeChallengeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetOverviewWithResponse request returning *GetOverviewResponse
func (c *ClientWithResponses) GetOverviewWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetOverviewResponse, error) {
	rsp, err := c.GetOverview(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetOverviewResponse(rsp)
}

// GenerateSubdomainWithResponse request returning *GenerateSubdomainResponse
func (c *ClientWithResponses) GenerateSubdomainWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GenerateSubdomainResponse, error) {
	rsp, err := c.GenerateSubdomain(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGenerateSubdomainResponse(rsp)
}

// SubdomainAcmeChallengeWithBodyWithResponse request with arbitrary body returning *SubdomainAcmeChallengeResponse
func (c *ClientWithResponses) SubdomainAcmeChallengeWithBodyWithResponse(ctx context.Context, subdomainId openapi_types.UUID, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*SubdomainAcmeChallengeResponse, error) {
	rsp, err := c.SubdomainAcmeChallengeWithBody(ctx, subdomainId, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubdomainAcmeChallengeResponse(rsp)
}

func (c *ClientWithResponses) SubdomainAcmeChallengeWithResponse(ctx context.Context, subdomainId openapi_types.UUID, body SubdomainAcmeChallengeJSONRequestBody, reqEditors ...RequestEditorFn) (*SubdomainAcmeChallengeResponse, error) {
	rsp, err := c.SubdomainAcmeChallenge(ctx, subdomainId, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseSubdomainAcmeChallengeResponse(rsp)
}

// ParseGetOverviewResponse parses an HTTP response from a GetOverviewWithResponse call
func ParseGetOverviewResponse(rsp *http.Response) (*GetOverviewResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetOverviewResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest OverviewResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGenerateSubdomainResponse parses an HTTP response from a GenerateSubdomainWithResponse call
func ParseGenerateSubdomainResponse(rsp *http.Response) (*GenerateSubdomainResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GenerateSubdomainResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest NewSubdomainResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}

// ParseSubdomainAcmeChallengeResponse parses an HTTP response from a SubdomainAcmeChallengeWithResponse call
func ParseSubdomainAcmeChallengeResponse(rsp *http.Response) (*SubdomainAcmeChallengeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &SubdomainAcmeChallengeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 429:
		var dest ErrorResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON429 = &dest

	}

	return response, nil
}
