linters:
  enable-all: true
  disable:
    - nosnakecase
    - interfacer
    - deadcode
    - exhaustivestruct
    - ifshort
    - structcheck
    - golint
    - varcheck
    - maligned
    - scopelint
    - structcheck
    - gomnd
    - varnamelen
    - exhaustruct
    - gocognit
    - wrapcheck
    - nestif
    - cyclop
    - ireturn
    - bodyclose
linters-settings:
  gocritic:
    disabled-checks:
      - ifElseChain
  funlen:
    # Checks the number of lines in a function.
    # If lower than 0, disable the check.
    # Default: 60
    lines: 120
    # Checks the number of statements in a function.
    # If lower than 0, disable the check.
    # Default: 40
    statements: 60
