// Package v1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package v1

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/deepmap/oapi-codegen/pkg/runtime"
	openapi_types "github.com/deepmap/oapi-codegen/pkg/types"
	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// ErrorResponse defines model for ErrorResponse.
type ErrorResponse struct {
	Error   string `json:"error"`
	Message string `json:"message"`
}

// NewSubdomainResponse New Subdomain Response.
type NewSubdomainResponse struct {
	// Id Subdomain ID.
	Id openapi_types.UUID `json:"id"`

	// Token Control Token.
	Token string `json:"token"`
}

// OverviewResponse defines model for OverviewResponse.
type OverviewResponse struct {
	// Version Server Version.
	Version string `json:"version"`
}

// SubdomainAcmeChallengeRequest Subdomain ACME Challenge Request.
type SubdomainAcmeChallengeRequest struct {
	// Token Control Token.
	Token string `json:"token"`

	// Values ACME Tokens.
	Values []string `json:"values"`
}

// SubdomainAcmeChallengeJSONRequestBody defines body for SubdomainAcmeChallenge for application/json ContentType.
type SubdomainAcmeChallengeJSONRequestBody = SubdomainAcmeChallengeRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Server Overview
	// (GET /)
	Overview(w http.ResponseWriter, r *http.Request)
	// Request new subdomain
	// (POST /subdomain)
	NewSubdomain(w http.ResponseWriter, r *http.Request)
	// Set ACME challenge tokens
	// (POST /subdomain/{subdomainId}/acme-challenge)
	SubdomainAcmeChallenge(w http.ResponseWriter, r *http.Request, subdomainId openapi_types.UUID)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Overview operation middleware
func (siw *ServerInterfaceWrapper) Overview(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Overview(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// NewSubdomain operation middleware
func (siw *ServerInterfaceWrapper) NewSubdomain(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.NewSubdomain(w, r)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

// SubdomainAcmeChallenge operation middleware
func (siw *ServerInterfaceWrapper) SubdomainAcmeChallenge(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()

	var err error

	// ------------- Path parameter "subdomainId" -------------
	var subdomainId openapi_types.UUID

	err = runtime.BindStyledParameterWithLocation("simple", false, "subdomainId", runtime.ParamLocationPath, chi.URLParam(r, "subdomainId"), &subdomainId)
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "subdomainId", Err: err})
		return
	}

	var handler http.Handler = http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SubdomainAcmeChallenge(w, r, subdomainId)
	})

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r.WithContext(ctx))
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshallingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshallingParamError) Error() string {
	return fmt.Sprintf("Error unmarshalling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshallingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/", wrapper.Overview)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subdomain", wrapper.NewSubdomain)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/subdomain/{subdomainId}/acme-challenge", wrapper.SubdomainAcmeChallenge)
	})

	return r
}

type OverviewRequestObject struct {
}

type OverviewResponseObject interface {
	VisitOverviewResponse(w http.ResponseWriter) error
}

type Overview200JSONResponse OverviewResponse

func (response Overview200JSONResponse) VisitOverviewResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NewSubdomainRequestObject struct {
}

type NewSubdomainResponseObject interface {
	VisitNewSubdomainResponse(w http.ResponseWriter) error
}

type NewSubdomain200JSONResponse NewSubdomainResponse

func (response NewSubdomain200JSONResponse) VisitNewSubdomainResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type NewSubdomain429JSONResponse ErrorResponse

func (response NewSubdomain429JSONResponse) VisitNewSubdomainResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

type SubdomainAcmeChallengeRequestObject struct {
	SubdomainId openapi_types.UUID `json:"subdomainId"`
	Body        *SubdomainAcmeChallengeJSONRequestBody
}

type SubdomainAcmeChallengeResponseObject interface {
	VisitSubdomainAcmeChallengeResponse(w http.ResponseWriter) error
}

type SubdomainAcmeChallenge200Response struct {
}

func (response SubdomainAcmeChallenge200Response) VisitSubdomainAcmeChallengeResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type SubdomainAcmeChallenge403JSONResponse ErrorResponse

func (response SubdomainAcmeChallenge403JSONResponse) VisitSubdomainAcmeChallengeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(403)

	return json.NewEncoder(w).Encode(response)
}

type SubdomainAcmeChallenge429JSONResponse ErrorResponse

func (response SubdomainAcmeChallenge429JSONResponse) VisitSubdomainAcmeChallengeResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(429)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// Server Overview
	// (GET /)
	Overview(ctx context.Context, request OverviewRequestObject) (OverviewResponseObject, error)
	// Request new subdomain
	// (POST /subdomain)
	NewSubdomain(ctx context.Context, request NewSubdomainRequestObject) (NewSubdomainResponseObject, error)
	// Set ACME challenge tokens
	// (POST /subdomain/{subdomainId}/acme-challenge)
	SubdomainAcmeChallenge(ctx context.Context, request SubdomainAcmeChallengeRequestObject) (SubdomainAcmeChallengeResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, args interface{}) (interface{}, error)

type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// Overview operation middleware
func (sh *strictHandler) Overview(w http.ResponseWriter, r *http.Request) {
	var request OverviewRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Overview(ctx, request.(OverviewRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Overview")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(OverviewResponseObject); ok {
		if err := validResponse.VisitOverviewResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// NewSubdomain operation middleware
func (sh *strictHandler) NewSubdomain(w http.ResponseWriter, r *http.Request) {
	var request NewSubdomainRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.NewSubdomain(ctx, request.(NewSubdomainRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "NewSubdomain")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(NewSubdomainResponseObject); ok {
		if err := validResponse.VisitNewSubdomainResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// SubdomainAcmeChallenge operation middleware
func (sh *strictHandler) SubdomainAcmeChallenge(w http.ResponseWriter, r *http.Request, subdomainId openapi_types.UUID) {
	var request SubdomainAcmeChallengeRequestObject

	request.SubdomainId = subdomainId

	var body SubdomainAcmeChallengeJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SubdomainAcmeChallenge(ctx, request.(SubdomainAcmeChallengeRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SubdomainAcmeChallenge")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SubdomainAcmeChallengeResponseObject); ok {
		if err := validResponse.VisitSubdomainAcmeChallengeResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("Unexpected response type: %T", response))
	}
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xWTXPbNhD9Kxi0h3ZGEhXbdWqemlg56OA2tT2dTDI+gMBSQkoADADK4Xj43zsLiB8S",
	"adeJe+xFQxHYr7fv7fKBcqNKo0F7R9MH6vgWFAuP76w19hpcabQDfFFaU4L1EsIx4DE++LoEmlLnrdQb",
	"2syoAufYBibOmhm18KWSFgRNP+1d9AZ3M+qlL9DiMPisdWSyz8A9Bvkd7m+qTBjFpB4mKcBxK0svjaYp",
	"3iLdNdLeW9DZUTFSjG17u/UKLXJjFfM0pVUlRZ9SX7c3f4Me+7k02ltTkFs8XowNj0CJvoOrAR6T5U7A",
	"8scO7E7C/eN924F1IbFRvWB3YMlf8fzfE20dDbIcRZ/IsCvjDVdwuWVFAXoD1/ClAuef6sKby6t3pDMg",
	"e4txL7+zDTO6Y0UVXRxahsDBzKGd9KDcNPHZ13U8fLXs/DNrWT0CLybZxRxg+DQ+I0DRsdS5wYS40Z7x",
	"ACIoJguatq9+E7VeCGnRZEY1U+hi8K6ZHddceaOYB0FKa7zhpiC5sUQ6V0m9IUwLophmG/wjas2U5Kwo",
	"asKKwvBg59o6AmiF5LCnoxSgvcwlWJrSq/VtnxD+aXokVtHvQMBXGBIUaE/et2n9tLpZXf2MULbEpq8W",
	"S/RjStCslDSlpwt8NaMl89vQugR/NjDBt2vwldWOME3Mns3E5MRvgbggEKwG6cbQYC0GrKfY4kj8EORk",
	"uWy7AjqEYmVZSB4sk88uihC+MlUWcCBNrCDWEOcxHv5oIacp/SHpB3ayn9bJSHeBFsdC4hycWwQqukop",
	"Zute9V0NeJp0vQvjw7hJnAIhCSMa7vtmj9EZTq4XI4Rzmp5dvM7PgbP5+cnr8/nZxcXpPMshm/9yyrMs",
	"y9h5vvy1m6Ep/fhhu80+vHUf/3w+oJPjdhLUlpod8RcY5ezk4tsK229T6o2ZK6bruY34usF6TOmtMSi7",
	"mrSnZMt2QDIATRQTQHJrFKlNZcn6PWFC2Njx55Z9uHUn6h0ngGGPOdVy44AZR8xKHrrHtWgSxhXMeTvt",
	"HqfdDfi4CLq7JPTZhfH0BA2nx2qYCZYp8GAdTT8dh1uvOvF3nfYGkSXeYJCuhc9lJWoqzKF+7A2AoMMt",
	"4W0Fw8696POkuYuuwfm3RtTfxs6XSOnpfdYcLkYsuZkeEs8U3vL0+4Qn9Y4VUszbxTwQ3RZwCe6kABHJ",
	"RqQj2ngSLALxDhjyXwpuHdOKcf8fLY/rP7qMKzoqubL4AbT1vnRpkuxeLYbfO3fNPwEAAP//D89fH/oM",
	"AAA=",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
