baseURL = 'http://example.org/'
languageCode = 'en-gb'
title = 'dyn.direct'

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
[module.hugoVersion]
extended = true

# Controls how many words are printed in the content summary on the docs homepage.
# See https://gohugo.io/content-management/summaries/
summaryLength = 30

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "Docs"
url = "/docs/start"
weight = 2

[params]
homepage_button_link = '/docs/start'
homepage_button_text = 'Read The Docs'
#homepage_image = '/images/terminal.gif'
